/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type { Provider } from "@ethersproject/providers";
import { Contract, Signer, utils } from "ethers";

import type { IEd3LoyaltyPoints, IEd3LoyaltyPointsInterface } from "../../contracts/IEd3LoyaltyPoints";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_mintTokenNumber",
        type: "uint256",
      },
    ],
    name: "mint",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IEd3LoyaltyPoints__factory {
  static readonly abi = _abi;
  static createInterface(): IEd3LoyaltyPointsInterface {
    return new utils.Interface(_abi) as IEd3LoyaltyPointsInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): IEd3LoyaltyPoints {
    return new Contract(address, _abi, signerOrProvider) as IEd3LoyaltyPoints;
  }
}
