/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type { Provider } from "@ethersproject/providers";
import { Contract, Signer, utils } from "ethers";

import type { IEd3AirTicketNFT, IEd3AirTicketNFTInterface } from "../../contracts/IEd3AirTicketNFT";

const _abi = [
  {
    inputs: [],
    name: "maxSupply",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_to",
        type: "address",
      },
    ],
    name: "mint",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [],
    name: "mintPrice",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "totalSupply",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IEd3AirTicketNFT__factory {
  static readonly abi = _abi;
  static createInterface(): IEd3AirTicketNFTInterface {
    return new utils.Interface(_abi) as IEd3AirTicketNFTInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): IEd3AirTicketNFT {
    return new Contract(address, _abi, signerOrProvider) as IEd3AirTicketNFT;
  }
}
